name: Train and Inference YOLOv11 Model

on:
  push:
    branches:
      - master  # 当代码推送到 `master` 分支时触发工作流
  pull_request:
    branches:
      - master  # 当向 `master` 分支发起拉取请求时触发工作流

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install ultralytics

  train:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train YOLOv11 Model
        run: |
          python train.py --img 640 --batch-size 16 --epochs 50 --data data.yaml --cfg yolov11.yaml --nc 5 --weights yolov11n.pt --name my_yolov11_model

      - name: Upload training results
        uses: actions/upload-artifact@v4
        with:
          name: training-results
          path: runs/train/my_yolov11_model/

  inference:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run inference
        run: |
          python detect.py --weights runs/train/my_yolov11_model/weights/best.pt --img 640 --source mydata/test/images --save-txt --save-img --project runs/inference --name inference_results

      - name: Upload inference results
        uses: actions/upload-artifact@v4
        with:
          name: inference-results
          path: runs/inference/inference_results/
