name: Train and Inference YOLOv11 Model

on:
  push:
    branches:
      - master  # 每次将代码推送到 main 分支时触发训练


jobs:
  train:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的虚拟环境进行训练

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ultralytics

      # Step 4: Install PyTorch (if not included in requirements)
      - name: Install PyTorch
        run: |
          pip install torch==2.9.0 torchvision torchaudio   # 安装带有 CUDA 支持的 PyTorch
      # Step 5: Train YOLOv11 model
      - name: Train YOLOv11 model
        run: |
          python train.py --img 640 --batch 16 --epochs 100 --data ./mydata/data.yaml --cfg models/yolo11.yaml --weights yolo11n.pt --name yolov11_model
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}  # 可选：用于记录训练日志的 Weights & Biases API 密钥
          CUDA_VISIBLE_DEVICES: 0  # 可选：设置使用的 GPU 设备编号

      # Step 6: Inference with trained YOLOv11 model
      - name: Inference with YOLOv11 model
        run: |
          python detect.py --weights runs/train/yolov11_model/weights/best.pt --img 640 --conf 0.25 --source ./mydata/test/images  # 进行推理

      # Step 7: Upload training and inference results to GitHub artifact
      - name: Upload training and inference results to GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: yolov11-training-inference-results
          path: |
            runs/train/yolov11_model  # 上传训练结果文件夹
            runs/detect  # 上传推理结果文件夹
