name: Train and Inference YOLOv8 Model

on:
  push:
    branches:
      - main  # 每次将代码推送到 main 分支时触发训练


jobs:
  train:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本的虚拟环境进行训练

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ultralytics 

      # Step 4: Install PyTorch (if not included in requirements)
      - name: Install PyTorch
        run: |
          pip install torch torchvision torchaudio

      # Step 5: Train YOLOv11 model
      - name: Train YOLOv11 model
        run: |
          yolo mode=train model=yolo11n.pt data=data.yaml imgsz=640 epochs=100 batch=16
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}  # 可选：用于记录训练日志的 Weights & Biases API 密钥
          CUDA_VISIBLE_DEVICES: 0  # 可选：设置使用的 GPU 设备编号

      # Step 6: Inference with trained YOLOv11 model
      - name: Inference with YOLOv11 model
        run: |
          yolo mode=predict model=runs/train/exp/weights/best.pt source=./data/images imgsz=640 conf=0.25

      # Step 7: Upload training and inference results to GitHub artifact
      - name: Upload training and inference results to GitHub artifact
        uses: actions/upload-artifact@v2
        with:
          name: yolov8-training-inference-results
          path: |
            runs/train/exp  # 上传训练结果文件夹
            runs/predict  # 上传推理结果文件夹
